### ISSUE TITLE
Des guillemets dans la recherche font une erreur 500

### ISSUE THREAD

**Issue by alphoenix** [etalab/cada.data.gouv.fr#44]
J'espérais une recherche en expression exacte avec des guillemets mais ça me sort une erreur 500.

**Comment by taniki** [comment]
ça fonctionne en rajoutant le nom du champ devant la recherche. Les champs ne sont explicités nulle part. En fait cela correspond à la [syntaxe inline d'Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) (par exemple : `content:"data hub" -santé` renvoie le résultat de contenant la chaine mais exclu ceux avec `santé`).

## Exemple

requête : `content:"data hub"`

https://cada.data.gouv.fr/search?q=content%3A%22data+hub%22

## Actions

- [] documenter la syntaxe
- [] mieux gérer l'erreur
- [] rendre implicite que les doubles quotes sont une tentative d'exact match sur une chaine de caractère dans le champ de l'avis.

**Comment by taniki** [comment]
Voir #49 pour la doc
